apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - cronjob.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - migrate-job.yaml
  - servicemonitor.yaml

images:
  - name: 236510207573.dkr.ecr.ap-northeast-2.amazonaws.com/erpulse-api
    newTag: 11a87dc3781f2ee45e40a2aa7cda6a1799a8a438
