apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - cronjob.yaml
  - redis-deployment.yaml
  - redis-service.yaml

images:
  - name: 236510207573.dkr.ecr.ap-northeast-2.amazonaws.com/erpulse-api
    newTag: e292ec1ff4dd0ae836741705613403355ba7c90f